---

- name: run the playbook tasks on the localhost
  hosts: localhost
  become: yes

  tasks:

    - name: print out the hostname of target
      command: hostname

    - name: update the apt package index i.e. apt-get update
      apt: update_cache=yes
    
    - name: Install VIM Editor
      apt: pkg=vim state=installed update_cache=true
      notify:
        - start vim
